### ISSUE TITLE
Database Dump

### ISSUE THREAD

**Issue by rossedman** [lavmeiker/capistrano-wpcli#10]
Hey @lavmeiker,

Really like what you have done! Thanks for this gem. I have a question. Is there a way to `dump` a database rather than `push` or `pull`? For instance, I want my site to run a backup whenever I deploy just in case. 

Also, is there more examples? If there isn't could I commit some to your `.README`?

Thanks

**Comment by jeremyzahner** [comment]
This is pushed to the lux branch right now.

Will release it shortly.

**Comment by rossedman** [comment]
:+1: Thanks!
