### ISSUE TITLE
Question Vagrant

### ISSUE THREAD

**Issue by EkAndreas** [lavmeiker/capistrano-wpcli#12]
When using Vagrant, in our case ansible-bedrock, how to get db pull to work? Shouldnt the db dump download to the vagrant host? And from that place be executed?
Or is it designed to run the cap files within the vagrant machine?
Please, some examples would be worth gold :-)

**Comment by jeremyzahner** [comment]
So this should be solved by now after the merge of https://github.com/lavmeiker/capistrano-wpcli/issues/13.
