### ISSUE TITLE
Exception when rsync requires non-standard port or key

### ISSUE THREAD

**Issue by timkinnane** [lavmeiker/capistrano-wpcli#14]
Hey, thanks for this gem! I just have a little issue which I think can be easily fixed.

The `:uploads:rsync:push` task times out if the server requires a non-standard port or key setting.

I know I can set **wpcli_rsync_options** manually to change the port and/or keyfile settings, but those will already be defined in the stage's **ssh_options**, so it doesn't seem right to start adding configs that are already defined. Plus, I'm not that good with the Capistrano syntax so I'm hoping someone else will see this issue and deal with it better than me.

Ideally, I guess the task would check for the following settings in the current stage and join it to them with the appropriate flags in the rsync options array.

    set :ssh_options, {
      keys: %w(/home/user/.ssh/deploy_key),
      port: 4444
    }

Right?

**Comment by markstewie** [comment]
I've got exactly the same problem and totally agree that it would be awesome that it would be ideal if the port was taken from the environment ssh_options settings to include the port if it's there. Would love it if this was fixed to do this.

Did you ever find a way to get this working?

**Comment by timkinnane** [comment]
Nope sorry, I left out automated rsync for now. I spent too much time on my deployment setup and had to jump back to the actual build. I will look at it again in a couple weeks when my site goes to production.

**Comment by markstewie** [comment]
Bugger... I can see where I need to change it [https://github.com/lavmeiker/capistrano-wpcli/blob/master/lib/capistrano/tasks/wpuploads.rake]()... have forked and trying to add it in. Will let you know if I'm able to fix it...

**Comment by markstewie** [comment]
Got it to work!

Set 
`set :wpcli_rsync_options, '-avz -e "ssh -p <port number>"'` in your deploy/<env>.rb file.

Then... I had to ssh into my server and reset all permissions on the uploads folder to the user capistrano is using to ssh in. eg I ran `sudo chown -R deploy:deploy uploads`. Would love to know how to not have to do that step... but that's for another day.

Hope that helps.

**Comment by timkinnane** [comment]
Hey, good news. I think I tried that but also needed to select a keyfile. I
wanted to avoid setting options that were already defined in the stage
config too.

Regarding your permissions issue, I had the same thing, solved it by making
a post install action to set permissions:

  desc 'Set group permissions'
  task :mod_group do
    on roles(:web) do
      within release_path do
        execute 'chown', '-R', ':www-data', 'web'
        execute 'chmod', '-R', 'g+s', 'web'
        info "Group permission of www modified to www-data"
      end
    end
  end
  after :finished, 'deploy:mod_group'

That's all within `namespace :deploy do`

The g+s permissions actually sets a default owner and group for all future
file creation. So doing it every time isn't strictly necessary, it could be
done once manually and left out of the script entirely, but the point of a
deploy script is to avoid manual steps and not make assumptions that things
will be already set up.

Hope that helps.

Tim.

**Comment by markstewie** [comment]
Thanks Tim, that is awesome.. really helpful.

**Comment by timkinnane** [comment]
Just following up on this breadcrumb. I found out this Capistrano permissions gem:
https://github.com/capistrano/file-permissions

Handles similar to my custom task, with easier configuration.

**Comment by jeremyzahner** [comment]
Am i right that this is a file permission issue and not the gem's?

**Comment by jeremyzahner** [comment]
Issue again here: https://github.com/lavmeiker/capistrano-wpcli/issues/28

We will make sure to integrate a port config into the docs.

**Comment by jeremyzahner** [comment]
You can now specifiy a :wpcli_rsync_port var.
This will overwrite the default port.

This is pushed to the lux branch and will be published soon.

**Comment by jeremyzahner** [comment]
Hey Guys!

Sorry for the delay.

Now it works via

`set :ssh_options, {
  keys: %w(/home/user/.ssh/deploy_key),
  port: 4444
}`

See http://capistranorb.com/documentation/advanced-features/properties/#precedence for further instructions.
