### ISSUE TITLE
[Proposal] Backup DB upon wpcli:db:push

### ISSUE THREAD

**Issue by tommymarshall** [lavmeiker/capistrano-wpcli#17]
It's be great to pass an optional flag (`cap staging wpcli:db:push --backup="./backups/"`) to save a copy of the sql dump before deleting it, which would also be accessible via a separate taske `wpcli:db:backup`.

**Comment by davestevens** [comment]
I wanted this today, so I've just made a pull request with the feature if you're still interested (#27).

**Comment by jeremyzahner** [comment]
This is pushed to the lux branch right now.

Will release it shortly.
