### ISSUE TITLE
Pull / push database Multisite network

### ISSUE THREAD

**Issue by haroldangenent** [lavmeiker/capistrano-wpcli#20]
`wpcli_args` makes it possible to search & replace a database for a Multisite network. For example:

```
set :wpcli_args, '--skip-columns=guid --network --url=http://www.example.dev'
```

However, you **need** to pass `--url` to properly search & replace in a multisite network. This URL depends on your action: pushing or pulling.

So you need to change the configuration files every time you want to push or pull.

Would it be possible to include this argument in the actual command? For example:

```
cap staging wpcli:db:push --url=http://www.example.dev
```

**Comment by mikaelengstrom** [comment]
My branch of this plugin solves this:

https://github.com/mikaelengstrom/capistrano-wpcli/commit/04b63d14f4410215ed99e776efa93c2d1359e918

**Comment by jeremyzahner** [comment]
Since its merged i guess this should be resolved.
Let us know if not! =)
